language: rust
cache: cargo
rust:
  - stable
  - beta
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo install --force cargo-audit
  - cargo generate-lockfile
script:
  - cargo build
  - cargo fmt --all -- --check
  - cargo test
  - cargo clippy -- -D warnings
  - cargo audit
