[package]
name = "duo-auth-rs"
version = "0.1.4"
authors = ["James Brown <jbrown@easypost.com>", "Jared Greeno <jared@easypost.com>"]
description = "Small binary that implements Duo push authentication and incorporates a 'recent ip' whitelist"

[dependencies]
reqwest = "^0.7.3"
rust-crypto = "0.2"
clap = "2"
log = "^0.3"
env_logger = "^0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log-panics = { version = "1.1" , features = ["with-backtrace"] }
error-chain = "0.10"
url = "1"
itertools = "^0.6"
ipnetwork = "^0.12"
syslog = "^3.3.0"

[dependencies.rusqlite]
version = "^0.13"
features = ["bundled"]
